### ISSUE TITLE
Error in call isValidNumber by mb_strcut from namespace libphonenumber

### ISSUE THREAD

**Issue by enrisca** [misd-service-development/phone-number-bundle#178]
Attempted to call function \"mb_strcut\" from namespace \"libphonenumber\".","error":"#0 \/home\/enrsica\/Proyectos\/edigitaltrust\/crm-leads-api-core\/vendor\/giggsey\/libphonenumber-for-php\/src\/Matcher.php(96): libphonenumber\\Matcher->doMatch('lookingAt')\n#1 \/home\/enrsica\/Proyectos\/edigitaltrust\/crm-leads-api-core\/vendor\/giggsey\/libphonenumber-for-php\/src\/RegexBasedMatcher.php(50): libphonenumber\\Matcher->lookingAt()\n#2 \/home\/enrsica\/Proyectos\/edigitaltrust\/crm-leads-api-core\/vendor\/giggsey\/libphonenumber-for-php\/src\/RegexBasedMatcher.php(37): libphonenumber\\RegexBasedMatcher->match('666666666', '[5-9]\\\\d{8}', false)\n#3

Help, what could be happens?
thanks!!

**Comment by janjango** [comment]
I just solve this issue by running `sudo apt-get install php-mbstring` on Ubuntu 16.04
